### ISSUE TITLE
ImageMagick has serious security flaws

### ISSUE THREAD

**Issue by dlibanori** [tomasc/dragonfly_pdf#12]
Have you seen this?

https://imagetragick.com/

**Comment by tomasc** [comment]
Thanks @dlibanori, good point. 
I have recently switched to `ghostscript` and plan to be using to `libvips` instead soon.

**Comment by dlibanori** [comment]
I am working with dragonfly + pdf with ghostscript. It works nicely.

**Comment by tomasc** [comment]
0.3.0 has some breaking changes and uses `libvips`, enjoy!
https://github.com/tomasc/dragonfly_pdf/blob/master/CHANGELOG.md#030
