### ISSUE TITLE
pdf_properties doesn't take opts param

### ISSUE THREAD

**Issue by asgerb** [tomasc/dragonfly_pdf#2]
Getting `ArgumentError - wrong number of arguments (1 for 0)` when using `pdf_properties(spreads: true)`.

**Comment by tomasc** [comment]
Can you try to fix it?
Fork, add failing test, fix it, commit, send pull request.
?
T

**Comment by asgerb** [comment]
For sure! Tried to look at the dragonfly ImageMagick plugin to see how they allow the passing of the params, doesn’t seem different from what we have weirdly.

A

**Comment by tomasc** [comment]
I guess we should just return values for both options – with spreads & without.

The hash then could look like this:
```ruby
{
  info: pdf.info,

  aspect_ratios: aspect_ratios(pdf, false),
  heights: heights(pdf, false),
  page_count: page_count(pdf, false),
  page_numbers: page_numbers(pdf, false),
  spread_count: spread_count(pdf, false),
  widths: widths(pdf, false),

  spreads: {
    aspect_ratios: aspect_ratios(pdf, true),
    heights: heights(pdf, true),
    page_count: page_count(pdf, true),
    page_numbers: page_numbers(pdf, true),
    spread_count: spread_count(pdf, true),
    widths: widths(pdf, true),
  }
}
```

What do you think? Do you want to give it a shot?

T

**Comment by asgerb** [comment]
Cool, yeah I’ll give it a try ;)=
